version: '2.1'

services:
  nuevo:
    image: nuevo
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 4200:4200
      - 9876:9876
    volumes:
      - './:/usr/src/app'
      - '/usr/src/app/node_modules'
    command: "ng serve  --host 0.0.0.0 --port 4200 --disable-host-check"
    environment:
       - COMPOSE_HTTP_TIMEOUT=200
